(() => {
  'use strict';

  if (document.querySelector('.article-hero') && !document.querySelector('link[href="article.css"]')) { const s=document.createElement('link');s.rel='stylesheet';s.href='article.css';document.head.appendChild(s); }
  const pathname=window.location.pathname.split('/').pop()||'index.html';
  const storageKey='homeRoutineGuide.first30Days.v1';
  const starterCheckoutUrl='https://home-routine-guide.kit.com/products/19-starter-binder?step=checkout';
  const seasons={spring:{kicker:'Spring routine',title:'Inspect, refresh, and catch winter damage.',tasks:['Walk the exterior and note visible changes','Check gutters and make sure water can drain away','Prepare cooling equipment before hot weather','Review outdoor faucets, screens, seals, and weatherstripping']},summer:{kicker:'Summer routine',title:'Keep cooling, water, and outdoor areas in view.',tasks:['Check the HVAC filter and follow the equipment instructions','Look for signs of moisture around plumbing and appliances','Inspect decks, railings, steps, and exterior walking surfaces','Keep vegetation and debris away from exterior equipment']},fall:{kicker:'Fall routine',title:'Prepare the home before cold weather arrives.',tasks:['Schedule heating-system service when appropriate','Check doors, windows, and visible exterior gaps','Review gutters and drainage after leaves fall','Confirm winter tools and emergency supplies are accessible']},winter:{kicker:'Winter routine',title:'Monitor safety, moisture, and cold-weather stress.',tasks:['Test smoke and carbon-monoxide alarms','Keep exterior appliance vents clear and visible','Watch for leaks, condensation, and unusual indoor moisture','Review the home after storms and document new damage']}};

  const siteMenu=document.querySelector('.site-menu');if(siteMenu){siteMenu.id='site-menu';siteMenu.innerHTML=`<a href="/#start">Start Here</a><a href="resources.html#checklists">Free Checklists</a><a href="resources.html#guides">Guides</a><a href="resources.html#tools">Free Tools</a><a href="packages.html">Starter Binder</a><a class="nav-cta" href="/#launch">Newsletter</a>`;}
  const footerLinks=document.querySelector('.footer-links');if(footerLinks&&!footerLinks.querySelector('a[href="digital-product-terms.html"]')){const a=document.createElement('a');a.href='digital-product-terms.html';a.textContent='Digital Product Terms';footerLinks.appendChild(a);}
  const menuButton=document.querySelector('.menu-toggle'),menu=document.querySelector('#site-menu');if(menuButton&&menu){menuButton.setAttribute('aria-controls','site-menu');menuButton.addEventListener('click',()=>{const open=menu.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(open));});menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu.classList.remove('open');menuButton.setAttribute('aria-expanded','false');}));}

  const seasonContent=document.querySelector('#season-content'),seasonTabs=document.querySelectorAll('.season-tab');seasonTabs.forEach(tab=>tab.addEventListener('click',()=>{const season=seasons[tab.dataset.season];if(!season||!seasonContent)return;seasonTabs.forEach(item=>{const selected=item===tab;item.classList.toggle('active',selected);item.setAttribute('aria-selected',String(selected));});seasonContent.innerHTML=`<p class="season-kicker">${season.kicker}</p><h3>${season.title}</h3><ul>${season.tasks.map(t=>`<li>${t}</li>`).join('')}</ul>`;}));

  const toolCards=document.querySelectorAll('.tool-grid .tool-card'),budgetCard=toolCards[1];if(budgetCard){const badge=budgetCard.querySelector('.coming'),title=budgetCard.querySelector('h3'),description=budgetCard.querySelector('p');if(badge)badge.textContent='Free';if(title)title.textContent='Maintenance Budget Planner';if(description)description.textContent='Turn your own routine, project, and emergency-reserve assumptions into a clear monthly contribution.';if(!budgetCard.querySelector('a')){const link=document.createElement('a');link.className='text-link';link.href='maintenance-budget.html';link.textContent='Open the free planner →';budgetCard.appendChild(link);}}

  const printableGrid=document.querySelector('#printable-guides .resource-grid');
  if(printableGrid){
    if(!printableGrid.querySelector('a[href="home-maintenance-calendar-printable.html"]')){const card=document.createElement('article');card.className='resource-card';card.innerHTML='<span class="resource-type">Maintenance calendar</span><h3>Printable Home Maintenance Calendar</h3><p>Build a recurring schedule around your actual equipment, provider dates, seasonal needs, completion history, and next actions.</p><a href="home-maintenance-calendar-printable.html">Build the calendar →</a>';printableGrid.appendChild(card);}
    if(!printableGrid.querySelector('a[href="home-warranty-tracker-printable.html"]')){const card=document.createElement('article');card.className='resource-card';card.innerHTML='<span class="resource-type">Warranty tracker</span><h3>Printable Home Warranty Tracker</h3><p>Track model and serial numbers, receipts, coverage dates, registration, claim contacts, document locations, and repair history.</p><a href="home-warranty-tracker-printable.html">Build the warranty tracker →</a>';printableGrid.appendChild(card);}
  }

  const checklist=document.querySelector('#interactive-list'),progressText=document.querySelector('#checklist-progress-text'),progressBar=document.querySelector('#checklist-progress-bar'),resetButton=document.querySelector('#reset-checklist');if(checklist){const boxes=[...checklist.querySelectorAll('input[type="checkbox"][data-task]')];const read=()=>{try{const v=JSON.parse(localStorage.getItem(storageKey)||'[]');return Array.isArray(v)?v:[]}catch{return[]}};const save=()=>{try{localStorage.setItem(storageKey,JSON.stringify(boxes.filter(b=>b.checked).map(b=>b.dataset.task)))}catch{}};const update=()=>{const n=boxes.filter(b=>b.checked).length,total=boxes.length,pct=total?Math.round(n/total*100):0;if(progressText)progressText.textContent=`${n} of ${total} complete`;if(progressBar)progressBar.style.width=`${pct}%`;};const saved=new Set(read());boxes.forEach(b=>{b.checked=saved.has(b.dataset.task);b.addEventListener('change',()=>{save();update();});});resetButton?.addEventListener('click',()=>{boxes.forEach(b=>b.checked=false);try{localStorage.removeItem(storageKey)}catch{}update();});update();}

  const kitForm={hostedUrl:'https://home-routine-guide.kit.com/4f903c7d6d'};const addNewsletterStyles=()=>{if(document.querySelector('link[href="newsletter.css"]'))return;const s=document.createElement('link');s.rel='stylesheet';s.href='newsletter.css';document.head.appendChild(s);};const addCommerceScript=()=>{const src='https://home-routine-guide.kit.com/commerce.js',existing=document.querySelector(`script[src="${src}"]`);if(existing)return existing;const s=document.createElement('script');s.src=src;s.async=true;s.defer=true;s.dataset.homeRoutineKitCommerce='true';s.addEventListener('error',()=>s.remove(),{once:true});document.body.appendChild(s);return s;};const mountKitForm=container=>{if(!container||container.dataset.kitMounted==='true')return;container.dataset.kitMounted='true';const f=document.createElement('iframe');f.className='kit-form-frame';f.src='newsletter-embed.html?v=1';f.title='Subscribe to the Home Routine Guide newsletter';f.setAttribute('scrolling','no');f.setAttribute('loading','eager');container.replaceChildren(f);};const formShellMarkup=`<div class="newsletter-form-shell"><div class="kit-form-mount" aria-label="Email newsletter signup"></div><p class="newsletter-fallback">Form not appearing? <a href="${kitForm.hostedUrl}" target="_blank" rel="noopener noreferrer">Open the secure Kit signup form</a>.</p><p class="newsletter-privacy">By subscribing, you agree to receive Home Routine Guide emails. Unsubscribe anytime. See our <a href="privacy.html">privacy policy</a>.</p></div>`;

  const main=document.querySelector('main');const starterPromoPages=new Set(['resources.html','first-30-days.html','seasonal-maintenance.html','fall-home-maintenance-checklist.html','water-leak-guide.html','smoke-co-alarm-guide.html','where-is-main-water-shutoff.html','how-often-change-hvac-filter.html','monthly-home-maintenance-checklist.html','maintenance-budget.html','contractor-quote-comparison.html','home-inspection-report-action-plan.html','new-homeowner-checklist-printable.html','home-maintenance-binder-printable.html','home-maintenance-log-printable.html','new-house-maintenance-checklist.html','home-maintenance-records-to-keep.html','how-to-compare-contractor-estimates.html','new-homeowner-emergency-information-checklist.html','home-maintenance-calendar-printable.html','home-warranty-tracker-printable.html']);
  if(main&&starterPromoPages.has(pathname)&&!document.querySelector('.starter-product-section')){addNewsletterStyles();const section=document.createElement('section');section.className='starter-product-section';section.innerHTML=`<div class="container"><div class="starter-product-card"><div><p class="eyebrow">44-Page New Homeowner Starter Binder</p><h2>Know what to record—not just where to write it.</h2><p>The guided Starter Binder uses specific prompts and examples for shutoffs, home systems, equipment, warranties, service history, repairs, moisture incidents, contractors, maintenance, budgets, replacement planning, and projects.</p><ul class="starter-product-benefits"><li>44 guided printable pages</li><li>One-time $19 digital purchase</li><li>Instant file delivery through Kit</li><li>No subscription required</li></ul></div><div class="starter-product-actions"><a class="button button-primary convertkit-button" href="${starterCheckoutUrl}" data-commerce>Get the 44-Page Binder — $19</a><a class="button button-secondary" href="packages.html#preview">Preview the worksheets</a><p class="checkout-transition-note">Checkout opens on Kit. One-time $19 payment with instant digital delivery.</p></div></div></div>`;const launch=document.querySelector('#launch');if(launch)main.insertBefore(section,launch);else main.appendChild(section);addCommerceScript();}
  if(document.querySelector('a.convertkit-button[data-commerce]'))addCommerceScript();

  const launchCard=document.querySelector('#launch .launch-card');if(launchCard){addNewsletterStyles();launchCard.classList.add('newsletter-card');launchCard.innerHTML=`<div class="newsletter-copy"><p class="eyebrow">Free homeowner checklist</p><h2>Start your first 30 days with a plan.</h2><p>Join the Home Routine Guide newsletter and get the printable First 30 Days Homeowner Checklist, plus occasional practical homeowner guidance.</p><ul class="newsletter-benefits"><li>Printable First 30 Days workbook</li><li>Practical seasonal guidance</li><li>No daily spam</li></ul></div>${formShellMarkup}`;mountKitForm(launchCard.querySelector('.kit-form-mount'));}else{const newsletterPages=new Set(['first-30-days.html','seasonal-maintenance.html','fall-home-maintenance-checklist.html','water-leak-guide.html','smoke-co-alarm-guide.html','where-is-main-water-shutoff.html','how-often-change-hvac-filter.html','monthly-home-maintenance-checklist.html','maintenance-budget.html','contractor-quote-comparison.html','home-inspection-report-action-plan.html','home-maintenance-calendar-printable.html','home-warranty-tracker-printable.html']);if(main&&newsletterPages.has(pathname)){addNewsletterStyles();const section=document.createElement('section');section.className='newsletter-section';section.innerHTML=`<div class="container"><div class="newsletter-card"><div class="newsletter-copy"><p class="eyebrow">Free homeowner checklist</p><h2>Build a home routine you can keep.</h2><p>Get the First 30 Days Homeowner Checklist and occasional practical guidance for maintaining, organizing, and protecting your home.</p><ul class="newsletter-benefits"><li>Beginner-friendly priorities</li><li>Seasonal maintenance guidance</li><li>One-click unsubscribe</li></ul></div>${formShellMarkup}</div></div>`;main.appendChild(section);mountKitForm(section.querySelector('.kit-form-mount'));}}
  const year=document.querySelector('#year');if(year)year.textContent=String(new Date().getFullYear());
})();
